Used only for tests.

In [3]:
import pandas as pd

In [ ]:


data = {
    'Item': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam'],
    'Price': [1200, 25, 300, 75, 100],
    'Stock': [15, 50, 8, 22, 12],
    'Category': ['Hardware', 'Accessory', 'Hardware', 'Accessory', 'Accessory']
}

# We will set 'Item' as the index so we can use labels to find rows
df = pd.DataFrame(data).set_index('Item')

In [19]:
some1 = df.loc['Laptop',"Price"]
print(some1)

1200

In [20]:
accessories_prices = df.loc[df['Category'] == 'Accessory', 'Price']

print(accessories_prices)

Item
Mouse        25
Keyboard     75
Webcam      100
Name: Price, dtype: int64

In [ ]:
df_indexed = df.set_index('Category')



# Now let's look for 'Accessory'
accessories = df_indexed.loc['Accessory', 'Price']

print(accessories)

Category
Accessory     25
Accessory     75
Accessory    100
Name: Price, dtype: int64

In [31]:
category_index = df.reset_index().set_index('Category')
category_index.head()

               Item  Price  Stock
Category
Hardware     Laptop   1200     15
Accessory     Mouse     25     50
Hardware    Monitor    300      8
Accessory  Keyboard     75     22
Accessory    Webcam    100     12

In [46]:
d = {'A': [1, 2, 3, 4, 5,4],
        'B': [10, 20, 15, 25, 30,25]}
df = pd.DataFrame(d)

# Calculating mean, median, and mode
mean_values = df.mean()
median_values = df.median()
mode_values = df.mode().iloc[0] 

print(mean_values)
print(median_values)
print(mode_values)

A     3.166667
B    20.833333
dtype: float64
A     3.5
B    22.5
dtype: float64
A     4
B    25
Name: 0, dtype: int64

In [47]:
df.mode()

   A   B
0  4  25

In [53]:
d = {'A': [1, 2, 3, 4, 5],
        'B': [10, 12, 14, 16, 18]}
df = pd.DataFrame(d)
res = df.corr()
print(res)

     A    B
A  1.0  1.0
B  1.0  1.0

In [54]:
d = {'A': [1, 2, 3, 4, 5],
        'B': [10, 20, 15, 25, 30]}
df = pd.DataFrame(d)

# Calculating variance and standard deviation
variance_val = df.var()
std_dev_val = df.std()

print(variance_val)
print(std_dev_val)

A     2.5
B    62.5
dtype: float64
A    1.581139
B    7.905694
dtype: float64

In [55]:
d = {'A': [1, 2, 3, 4, 5],
        'B': [10, 20, 15, 25, 30]}
df = pd.DataFrame(d)

# Calculating skewness and kurtosis
skewness_val = df.skew()
kurtosis_val = df.kurt()

print(skewness_val)
print(kurtosis_val)

A    0.0
B    0.0
dtype: float64
A   -1.2
B   -1.2
dtype: float64

In [56]:
import pandas as pd

data = {
    'Steady_Suburbs': [490, 500, 510, 495, 505], # Everyone is middle class
    'Wild_Willow': [100, 150, 200, 250, 1800]    # 4 shacks and 1 massive billionaire mansion
}

# (Prices in thousands)
df = pd.DataFrame(data)

print("--- Skewness ---")
print(df.skew())

print("\n--- Kurtosis ---")
print(df.kurt())

--- Skewness ---
Steady_Suburbs    0.000000
Wild_Willow       2.203252
dtype: float64

--- Kurtosis ---
Steady_Suburbs   -1.200000
Wild_Willow       4.882879
dtype: float64

In [57]:
df = pd.DataFrame([[9, 4, 8, 9],
                   [8, 10, 7, 6],
                   [7, 6, 8, 5]],
                  columns=['Maths',  'English', 
                           'Science', 'History'])

print(df)

   Maths  English  Science  History
0      9        4        8        9
1      8       10        7        6
2      7        6        8        5

In [ ]:
df.sum() 
df.describe()

       Maths    English   Science   History
count    3.0   3.000000  3.000000  3.000000
mean     8.0   6.666667  7.666667  6.666667
std      1.0   3.055050  0.577350  2.081666
min      7.0   4.000000  7.000000  5.000000
25%      7.5   5.000000  7.500000  5.500000
50%      8.0   6.000000  8.000000  6.000000
75%      8.5   8.000000  8.000000  7.500000
max      9.0  10.000000  8.000000  9.000000

In [61]:
data = {
    'Item': ['Cake', 'Cake', 'Bread', 'Pastry', 'Cake'],
    'Flavor': ['Chocolate', 'Vanilla', 'Whole Wheat', 'Strawberry', 'Chocolate'],
    'Price': [250, 220, 80, 120, 250]
}

df = pd.DataFrame(data)
print(df)

     Item       Flavor  Price
0    Cake    Chocolate    250
1    Cake      Vanilla    220
2   Bread  Whole Wheat     80
3  Pastry   Strawberry    120
4    Cake    Chocolate    250

In [67]:
grouped = df.groupby('Flavor')
print(df.groupby('Item')['Price'].sum())

Item
Bread      80
Cake      720
Pastry    120
Name: Price, dtype: int64

In [68]:
print(df.groupby(['Item', 'Flavor'])['Price'].sum())

Item    Flavor
Bread   Whole Wheat     80
Cake    Chocolate      500
        Vanilla        220
Pastry  Strawberry     120
Name: Price, dtype: int64

In [71]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age')
print(sorted_df)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [72]:
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)

sorted_df = df_nan.sort_values(by="Age", na_position="first")
print(sorted_df)

      Name   Age
2  Charlie   NaN
1      Bob  22.0
3    David  22.0
0    Alice  28.0

In [75]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

df.set_index("Name")
df_sorted_by_index = df.sort_index()
print(df_sorted_by_index)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [76]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Age', kind='quicksort')
print(sorted_df)

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
0    Alice   28     85
4      Eve   28     88

In [78]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]
}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Name', key=lambda col: col.str.lower())
print(sorted_df)

      Name  Age  Score
0    Alice   28     85
1      Bob   22     90
2  Charlie   25     95
3    David   22     80
4      Eve   28     88

In [92]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4,5,6,7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
frames = [df, df1]
res1 = pd.concat(frames, ignore_index=True)
res1

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [102]:
res2 = pd.concat([df, df1], axis=1, join='inner')

res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

In [103]:
res2 = pd.concat([df, df1], axis=1, sort=False)

res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

In [104]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name':['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
        'Age':[17, 14, 12, 52],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [ ]:
frames = [df, df1 ]

res = pd.concat(frames, keys=['x', 'y'])
res

       Name  Age    Address Qualification
x 0     Jai   27     Nagpur           Msc
  1  Princi   24     Kanpur            MA
  2  Gaurav   22  Allahabad           MCA
  3    Anuj   32    Kannuaj           Phd
y 4    Abhi   17     Nagpur         Btech
  5  Ayushi   14     Kanpur           B.A
  6  Dhiraj   12  Allahabad          Bcom
  7  Hitesh   52    Kannuaj        B.hons

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [ ]:

res = pd.concat([df, s1], axis=1)

res

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

In [117]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}


data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}


df = pd.DataFrame(data1)


df1 = pd.DataFrame(data2)




print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons

In [119]:
res = pd.merge(df, df1, on='key')

res

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [ ]:

# Table 1: Price List
prices = {
    'Item': ['Shirt', 'Shirt', 'Pants', 'Pants'],
    'Size': ['S', 'L', 'S', 'L'],
    'Price': [20, 25, 30, 35]
}

# Table 2: Current Stock
stock = {
    'Item': ['Shirt', 'Shirt', 'Pants', 'Pants'],
    'Size': ['S', 'L', 'S', 'L'],
    'In_Stock': [10, 5, 8, 2]
}

df_prices = pd.DataFrame(prices)
df_stock = pd.DataFrame(stock)

# Merging on TWO keys
res = pd.merge(df_prices, df_stock, on=['Item', 'Size'])
print(res)

    Item Size  Price  In_Stock
0  Shirt    S     20        10
1  Shirt    L     25         5
2  Pants    S     30         8
3  Pants    L     35         2

In [123]:
# Left Table: Guests
df_guests = pd.DataFrame({
    'Name': ['Jai', 'Princi', 'Gaurav'],
    'Age': [27, 24, 22]
})

# Right Table: Food Preferences
df_food = pd.DataFrame({
    'Name': ['Jai', 'Princi', 'Anuj'],
    'Food': ['Pizza', 'Salad', 'Pasta']
})

# 1. INNER: Only people in BOTH lists (Jai and Princi)
inner = pd.merge(df_guests, df_food, on='Name', how='inner')

# 2. LEFT: All Guests (Gaurav stays, but has no Food -> NaN)
left = pd.merge(df_guests, df_food, on='Name', how='left')

# 3. OUTER: Everyone (Gaurav has no Food, Anuj has no Age -> both get NaNs)
outer = pd.merge(df_guests, df_food, on='Name', how='outer')

print("--- INNER ---")
print(inner)
print("\n--- LEFT ---")
print(left)
print("\n--- OUTER ---")
print(outer)

--- INNER ---
     Name  Age   Food
0     Jai   27  Pizza
1  Princi   24  Salad

--- LEFT ---
     Name  Age   Food
0     Jai   27  Pizza
1  Princi   24  Salad
2  Gaurav   22    NaN

--- OUTER ---
     Name   Age   Food
0    Anuj   NaN  Pasta
1  Gaurav  22.0    NaN
2     Jai  27.0  Pizza
3  Princi  24.0  Salad

In [128]:
# Players (Our "Left" Table)
df_players = pd.DataFrame({
    'Name': ['DragonSlayer', 'MagicMage', 'ShadowNinja']}, 
    index=['ID_1', 'ID_2', 'ID_3'])

# Equipment (Our "Right" Table)
# Notice: ID_2 is missing (Mage has no gear), and ID_4 is a mystery player
df_gear = pd.DataFrame({
    'Weapon': ['Steel Sword', 'Twin Daggers', 'Golden Bow']}, 
    index=['ID_1', 'ID_3', 'ID_4'])

# .join() defaults to a LEFT join
res = df_players.join(df_gear)
res

              Name        Weapon
ID_1  DragonSlayer   Steel Sword
ID_2     MagicMage           NaN
ID_3   ShadowNinja  Twin Daggers